name: TNTDefuse
main: net.corecrafted.tntdefuse.Main
version: 1.2
author: ThisTNTSquid
description: Simple plugin that defuse a TNT when clicking on a primed TNT
permissions:
  defuse.deactivate:
    description: Define permission for whether player can deactivate ignited TNT
    default: op
  defuse.pickup:
    description: Allow player with this permission to pickup primed TNT with a defined tool
    default: op
  defuse.item:
    description: Permission to give and define items in this plugin
    default: op
  defuse.reload:
    description: Reload the plugin config file
    default: op
  defuse.debug:
    description: Permission to check detail of item holding in hand
    default: op
commands:
  tntdefuse:
    description: Defuse plugin main command
    usage: /tntdefuse [args]